---
- name: Crear carpeta y archivo de texto en VM2
  hosts: all
  tasks:
    - name: Crear la carpeta 'mis_notas' en la VM2
      ansible.builtin.file:
        path: {{ansible_user_dir}}/mis_notas
        state: directory
        mode: '0755'

    - name: Crear el archivo hola.txt dentro de la carpeta
      ansible.builtin.copy:
        content: |
          =========================================
          Hola! Este archivo fue generado desde AWX
          Servidor de origen: VM1
          Servidor destino: VM3 ({{ inventory_hostname }})
          =========================================
        dest: {{ansible_user_dir}}/mis_notas/hola.txt
        mode: '0644'
